from typing import List, Dict, Any

DEMO_VULNERABILITIES: List[Dict[str, Any]] = [
    {
        "vulnerability_id": "CVE-2024-3094",
        "title": "XZ Utils Liblzma Upstream Backdoor Execution",
        "severity": "Critical",
        "cvss_score": 10.0,
        "epss_score": 0.96,
        "cisa_kev": 1,
        "asset_name": "Core SSH Bastion Prod",
        "asset_criticality": "Critical",
        "remediation_type": "Patch",
        "estimated_hours": 6.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Supply chain compromise inserting malicious code in liblzma within xz-utils enabling unauthenticated remote code execution.",
        "remediation_steps": "Downgrade xz-utils to version 5.4.6-1 across all Debian/Fedora bastion nodes and bounce sshd daemon."
    },
    {
        "vulnerability_id": "CVE-2024-21413",
        "title": "Microsoft Outlook Moniker Link Remote Code Execution",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.88,
        "cisa_kev": 1,
        "asset_name": "Executive Mail Cluster",
        "asset_criticality": "Critical",
        "remediation_type": "Patch",
        "estimated_hours": 1.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Flaw in parsing file:// moniker links bypassing Protected View and leaking NTLM hashes or executing code.",
        "remediation_steps": "Push Microsoft Security Update KB5034763 and disable automatic preview of untrusted attachments."
    },
    {
        "vulnerability_id": "CVE-2024-38077",
        "title": "Windows Remote Desktop Licensing Service Heap Overflow",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.79,
        "cisa_kev": 1,
        "asset_name": "Corporate Jump Host",
        "asset_criticality": "High",
        "remediation_type": "Isolation",
        "estimated_hours": 2.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Heap buffer overflow in RDLsvc.dll allowing unauthenticated remote attackers to execute code with SYSTEM privileges.",
        "remediation_steps": "Block TCP port 135 and dynamic RPC ports on perimeter firewalls and disable RDLsvc on non-licensing servers."
    },
    {
        "vulnerability_id": "CVE-2023-38606",
        "title": "WebKit Kernel State Manipulation Zero-Day",
        "severity": "High",
        "cvss_score": 8.2,
        "epss_score": 0.72,
        "cisa_kev": 1,
        "asset_name": "Customer Portal Frontend",
        "asset_criticality": "High",
        "remediation_type": "Configuration",
        "estimated_hours": 1.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Memory manipulation flaw permitting malicious web content to bypass kernel memory protections.",
        "remediation_steps": "Apply Safari runtime patch and configure CSP header to forbid unsafe eval and inline scripts."
    },
    {
        "vulnerability_id": "CVE-2024-28987",
        "title": "SolarWinds ARM Hardcoded Key Auth Bypass",
        "severity": "High",
        "cvss_score": 9.1,
        "epss_score": 0.62,
        "cisa_kev": 0,
        "asset_name": "Identity & Access Controller",
        "asset_criticality": "Critical",
        "remediation_type": "Credential Rotation",
        "estimated_hours": 1.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Hardcoded symmetric key allows unauthenticated actors to decrypt internal access tokens and escalate to Domain Admin.",
        "remediation_steps": "Deploy SolarWinds ARM 2024.3 hotfix and regenerate service master encryption certificate."
    },
    {
        "vulnerability_id": "CVE-2024-21626",
        "title": "runc Container Breakout via Leaked File Descriptor",
        "severity": "Critical",
        "cvss_score": 8.6,
        "epss_score": 0.68,
        "cisa_kev": 0,
        "asset_name": "Kubernetes Prod Worker Nodes",
        "asset_criticality": "Critical",
        "remediation_type": "Patch",
        "estimated_hours": 3.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Internal file descriptor leak in runc init allows container process to overwrite host filesystem binaries.",
        "remediation_steps": "Cordon and drain worker nodes, upgrade containerd/runc to 1.1.12, uncordon nodes sequentially."
    },
    {
        "vulnerability_id": "CVE-2023-48795",
        "title": "Terrapin SSH Protocol Prefix Truncation Attack",
        "severity": "Medium",
        "cvss_score": 5.9,
        "epss_score": 0.18,
        "cisa_kev": 0,
        "asset_name": "Internal Build Server",
        "asset_criticality": "Medium",
        "remediation_type": "Configuration",
        "estimated_hours": 0.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Cryptographic flaw in SSH protocol state sequence manipulation during handshake under ChaCha20-Poly1305 / CBC-EtM.",
        "remediation_steps": "Update sshd_config to remove chacha20-poly1305@openssh.com and enforce strict KEX negotiation extension."
    },
    {
        "vulnerability_id": "CVE-2024-4577",
        "title": "PHP CGI Argument Injection Argument Parsing RCE",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.85,
        "cisa_kev": 1,
        "asset_name": "Billing Web Gateway",
        "asset_criticality": "High",
        "remediation_type": "WAF Rule",
        "estimated_hours": 0.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Best-fit mapping character decoding in Windows PHP-CGI allows command injection via query string parameters.",
        "remediation_steps": "Add Cloudflare / Nginx WAF rule blocking query strings with '%ad' and upgrade PHP runtime to 8.2.20."
    },
    {
        "vulnerability_id": "CVE-2024-0012",
        "title": "PAN-OS Management Interface Authentication Bypass",
        "severity": "Critical",
        "cvss_score": 9.3,
        "epss_score": 0.76,
        "cisa_kev": 1,
        "asset_name": "Enterprise Perimeter Firewall",
        "asset_criticality": "Critical",
        "remediation_type": "Patch",
        "estimated_hours": 4.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Unauthenticated administrator session hijack via HTTP request header manipulation on management web interface.",
        "remediation_steps": "Restrict management interface access strictly to trusted internal management subnets and apply Hotfix 11.1.2-h4."
    },
    {
        "vulnerability_id": "CVE-2024-3400",
        "title": "PAN-OS GlobalProtect Gateway Arbitrary Command Injection",
        "severity": "Critical",
        "cvss_score": 10.0,
        "epss_score": 0.94,
        "cisa_kev": 1,
        "asset_name": "GlobalProtect VPN Node",
        "asset_criticality": "High",
        "remediation_type": "Configuration",
        "estimated_hours": 1.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Command injection vulnerability in GlobalProtect feature allowing unauthenticated root OS command execution.",
        "remediation_steps": "Disable device telemetry and apply threat prevention signature 95187 until hotfix is deployed."
    },
    {
        "vulnerability_id": "CVE-2024-27198",
        "title": "JetBrains TeamCity Authentication Bypass in Web Component",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.81,
        "cisa_kev": 1,
        "asset_name": "CI/CD Pipeline Master",
        "asset_criticality": "High",
        "remediation_type": "Patch",
        "estimated_hours": 2.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Path traversal in TeamCity web controller enabling full administrative account creation and remote code execution.",
        "remediation_steps": "Upgrade TeamCity server instance to 2023.11.4 and revoke any newly created administrator tokens."
    },
    {
        "vulnerability_id": "CVE-2023-46805",
        "title": "Ivanti Connect Secure Authentication Bypass",
        "severity": "Critical",
        "cvss_score": 8.2,
        "epss_score": 0.89,
        "cisa_kev": 1,
        "asset_name": "Contractor VPN Appliance",
        "asset_criticality": "Medium",
        "remediation_type": "Configuration",
        "estimated_hours": 1.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Control check bypass in web components of Ivanti Connect Secure allowing access to restricted endpoints.",
        "remediation_steps": "Import vendor XML mitigation file mitigation.xml and run Integrity Checker Tool (ICT)."
    },
    {
        "vulnerability_id": "CVE-2024-23897",
        "title": "Jenkins CLI Arbitrary File Read Vulnerability",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.74,
        "cisa_kev": 0,
        "asset_name": "Staging Automation Server",
        "asset_criticality": "Medium",
        "remediation_type": "Configuration",
        "estimated_hours": 0.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "args4j library character expansion parses @ character allowing unauthenticated reading of first lines of arbitrary files.",
        "remediation_steps": "Disable CLI over WebSocket / HTTP in Jenkins System Configuration or upgrade Jenkins core to 2.442."
    },
    {
        "vulnerability_id": "CVE-2024-1709",
        "title": "ConnectWise ScreenConnect Authentication Bypass",
        "severity": "Critical",
        "cvss_score": 10.0,
        "epss_score": 0.92,
        "cisa_kev": 1,
        "asset_name": "Remote Support Server",
        "asset_criticality": "High",
        "remediation_type": "Patch",
        "estimated_hours": 1.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Setup wizard re-execution path traversal allowing creation of an unauthorized administrative account.",
        "remediation_steps": "Update ScreenConnect server to version 23.9.8 immediately and audit user.xml database."
    },
    {
        "vulnerability_id": "CVE-2023-3519",
        "title": "Citrix ADC / NetScaler Unauthenticated Remote Code Execution",
        "severity": "Critical",
        "cvss_score": 9.8,
        "epss_score": 0.91,
        "cisa_kev": 1,
        "asset_name": "Reverse Proxy Load Balancer",
        "asset_criticality": "Critical",
        "remediation_type": "Patch",
        "estimated_hours": 3.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Stack buffer overflow in nsppe binary when handling AAA SAML authentication requests.",
        "remediation_steps": "Install Citrix firmware upgrade build 13.1-49.13 and verify HA node synchronization."
    },
    {
        "vulnerability_id": "CVE-2024-21887",
        "title": "Ivanti EPMM Command Injection in Management API",
        "severity": "High",
        "cvss_score": 8.8,
        "epss_score": 0.65,
        "cisa_kev": 1,
        "asset_name": "Mobile Device Manager",
        "asset_criticality": "Medium",
        "remediation_type": "WAF Rule",
        "estimated_hours": 0.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Command injection vulnerability in web components enabling execution of arbitrary commands as root.",
        "remediation_steps": "Apply regex filtering on WAF for '/api/v1/cav/client/status' requests and update RPM package."
    },
    {
        "vulnerability_id": "CVE-2024-20353",
        "title": "Cisco Adaptive Security Appliance WebVPN Denial of Service",
        "severity": "Medium",
        "cvss_score": 6.5,
        "epss_score": 0.15,
        "cisa_kev": 0,
        "asset_name": "Branch Office Edge Router",
        "asset_criticality": "Low",
        "remediation_type": "Configuration",
        "estimated_hours": 1.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Improper input validation in WebVPN web server causing device crash and reload under sustained requests.",
        "remediation_steps": "Apply Cisco ASA Software Release 9.18.4 and enable control plane policing."
    },
    {
        "vulnerability_id": "CVE-2024-29972",
        "title": "Zyxel NAS Command Injection via setCookie Parameter",
        "severity": "High",
        "cvss_score": 8.8,
        "epss_score": 0.58,
        "cisa_kev": 1,
        "asset_name": "Local Backup Storage NAS",
        "asset_criticality": "Low",
        "remediation_type": "Isolation",
        "estimated_hours": 0.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Command injection in setCookie endpoint in web management interface allowing OS command execution.",
        "remediation_steps": "Isolate NAS unit behind isolated VLAN with no direct internet ingress and update firmware."
    },
    {
        "vulnerability_id": "CVE-2024-24919",
        "title": "Check Point Quantum Gateway Zero-Day Info Disclosure",
        "severity": "High",
        "cvss_score": 8.6,
        "epss_score": 0.77,
        "cisa_kev": 1,
        "asset_name": "Data Center Security Gateway",
        "asset_criticality": "High",
        "remediation_type": "Patch",
        "estimated_hours": 2.0,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Unauthenticated path traversal vulnerability allowing reading of /etc/shadow and Active Directory passwords.",
        "remediation_steps": "Deploy Check Point hotfix Jumbo HF Take 55 and enforce password reset for local administrator accounts."
    },
    {
        "vulnerability_id": "CVE-2024-6387",
        "title": "regreSSHion OpenSSH Unauthenticated Signal Handler Race RCE",
        "severity": "High",
        "cvss_score": 8.1,
        "epss_score": 0.45,
        "cisa_kev": 0,
        "asset_name": "Dev & Test Linux Fleet",
        "asset_criticality": "Medium",
        "remediation_type": "Patch",
        "estimated_hours": 2.5,
        "actual_hours": 0.0,
        "status": "pending",
        "description": "Signal handler race condition in OpenSSH server on glibc-based Linux systems allowing remote code execution as root.",
        "remediation_steps": "Upgrade openssh-server package to 9.8p1-1 or set 'LoginGraceTime 0' in /etc/ssh/sshd_config as interim workaround."
    }
]
